## テンプレート内容 ##
# SNSを新規作成（サブスクリプションはEmail）
# 
# - xxxxxx     : Emailアドレス
#
## テンプレートチェックとデプロイ(コマンド例) ##
# aws cloudformation validate-template --template-body file://sns-subscription-email.yaml --profile default
# aws cloudformation deploy --template-file sns-subscription-email.yaml --stack-name sns-subscription-email --region ap-northeast-1 
#
AWSTemplateFormatVersion: 2010-09-09
Description: "sns create subscription email"

Parameters:
  SNSTopicName:
    Type: String
    Default: lambda-AddMetaS3-DL

Resources:

  CreateSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref SNSTopicName

  CreateSNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: xxxxxxx
      Protocol: email
      Region: ap-northeast-1
      TopicArn: !Ref CreateSNSTopic
